# Generated by Django 4.0 on 2021-12-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MEN', 'For Mens'), ('WOMAN', 'For Woman'), ('CHILD', 'For children'), ('UNI', 'Unisex')], default='UNI', max_length=5),
        ),
    ]
