import { makeStyles } from '@material-ui/core/styles';
import photo from '../../assets/1.jpg'

export default makeStyles((theme) => ({
  container: {
    width: 1200,
    height: 600,
    marginTop: 60,
    marginLeft:34,
    display: 'flex',
    position: 'relative',
    overflow: 'hidden',
  },
  imgContainer: {
    height: 500,
    flex:1,
  },
  image: {
    height: '90%',
  },
  infoContainer: {
    flex: 1,
    padding:30,
  },
  title: {
    fontSize:70,
  },
  desc: {
    marginTop: 50,
    marginLeft: 0,
    fontSize: 20,
    fontWeight: 500,
    letterSpacing:3,
  },
  container2:{
    height: 570,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 500,
    letterSpacing:3,
    position:'relative',
    backgroundAttachment: 'fixed',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundImage: `url(${photo})`,
    overflow: 'hidden',
    display: 'block',
    boxSizing: 'border-box',
    marginLeft:34,
    marginBottom:5,
  },
  container3: {
    maxWidth: 1050,
    width: '100%',
    paddingRight: 15,
    paddingLeft: 15,
    marginRight: 'auto',
    marginLeft: '10%',
    display: 'block',
    overflow:'hidden',
    position:'relative',
  },
  row:{
    display: 'flex',
    flexWrap: 'wrap',
    marginRight: -15,
    marginLeft: -15,
    paddingRight:15,
    paddingLeft:15,
  },
  maintitle: {
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 700,
  },
  imgContainer2: {
    position: 'relative',
    paddingRight:305,
    paddingLeft:5,
    marginLeft:-50,
    textAlign:'right',
  },
  announcing :{
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    position: 'relative',
    marginLeft: 40,
    marginBottom: 60,
    boxSizing: 'border-box',
  },
  imageAnnounce1:{
    marginTop:40,
    marginLeft:-5,
    borderRadius: 15,
    overflow: 'hidden',
    maxHeight: 400,
    width: 'auto',
    verticalAlign: 'middle',
    borderStyle: 'none',
    opacity: 0.7,
  },
  imageAnnounce2:{
    marginTop:20,
    marginLeft:-2,
    borderRadius: 15,
    overflow: 'hidden',
    height: 400,
    width: 'auto',
    verticalAlign: 'middle',
    opacity: 0.7,
  },
  imageAnnounce3:{
    borderRadius: 15,
    overflow: 'hidden',
    maxHeight: 400,
    width: 280,
    verticalAlign: 'middle',
    borderStyle: 'none',
    zIndex:1
  },
  textContainer: {
    position: 'absolute',
    marginTop:-580,
    marginLeft:440,
    width:'100%',
    paddingRight: 15,
    paddingLeft: 15,
    textAlign: 'left',
    marginBottom: 0,
    zIndex:2,
  },
  title3:{
    width:500,
  },
  button: {
    background: '#FFB6C1	',
    width:150,
    fontSize: 15,
    borderRadius: 3,
    border: 0,
    height: 48,
    textAlign: 'center',
    paddingTop:7,
},

}));
// infosContainer: {
//   width: 1800,
//   marginLeft:60,
//   padding:50,
// },
// info1Container: {
//   display: "inline-block",
//   width: 260,
//   margin: 0,
//   padding: 0,
// },